const WHATSAPP = '923255129241';

const PRODUCTS = [
  {id:'cream-1',name:'Vitamin C Cream',cat:'Creams',price:950,desc:'Brightens skin & boosts radiance with Vitamin C',img:'images/cream-vitamin-c.png'},
  {id:'cream-2',name:'Anti Aging Cream',cat:'Creams',price:1200,desc:'Reduces fine lines & restores youthful skin',img:'images/cream-anti-aging.png'},
  {id:'cream-3',name:'Anti Acne Cream',cat:'Creams',price:900,desc:'Clears acne & prevents future breakouts',img:'images/cream-anti-acne.png'},
  {id:'cream-4',name:'Anti Freckles Cream',cat:'Creams',price:1000,desc:'Fades freckles & evens skin tone',img:'images/cream-anti-freckles.png'},
  {id:'cream-5',name:'Vitamin B-3 Cream',cat:'Creams',price:1100,desc:'Niacinamide formula for smooth & clear skin',img:'images/cream-vitamin-b3.png'},
  {id:'cream-6',name:'Brightening Cream',cat:'Creams',price:1050,desc:'Brightens & evens skin tone for radiant complexion',img:'images/cream-brightening.png'},
  {id:'cream-7',name:'Extra Soft Moisturizing Cream',cat:'Creams',price:950,desc:'Ultra-light cream for deep 24-hour skin hydration',img:'images/cream-extra-soft.png'},
  {id:'cream-8',name:'Night Cream',cat:'Creams',price:1100,desc:'Overnight repair & renewal for revitalized skin',img:'images/cream-night.png'},
  {id:'cream-9',name:'Head and Foot Cream',cat:'Creams',price:850,desc:'Intensive care cream for dry heels & scalp',img:'images/cream-head-foot.png'},
  {id:'cream-10',name:'Fairness Cream',cat:'Creams',price:1050,desc:'Whitening & brightening formula for even skin tone',img:'images/cream-fairness.png'},
  {id:'cream-11',name:'Oil-Free Gel',cat:'Creams',price:900,desc:'Lightweight oil-free gel for clear & matte skin',img:'images/cream-oil-free-gel.png'},
  {id:'cream-12',name:'Moisturizer',cat:'Creams',price:880,desc:'Daily moisturizer for soft, smooth & nourished skin',img:'images/cream-moisturizer.png'},
  {id:'cream-13',name:'BB Cream',cat:'Creams',price:1200,desc:'Blemish balm with coverage, moisture & SPF protection',img:'images/cream-bb.png'},
  {id:'cream-14',name:'Sunblock SPF 30',cat:'Creams',price:750,desc:'Everyday sun protection with SPF 30 formula',img:'images/cream-spf30.png'},
  {id:'cream-15',name:'Sunblock SPF 50',cat:'Creams',price:850,desc:'High protection sunblock with SPF 50 shield',img:'images/cream-spf50.png'},
  {id:'cream-16',name:'Sunblock SPF 60',cat:'Creams',price:950,desc:'Advanced broad-spectrum SPF 60 sun protection',img:'images/cream-spf60.png'},
  {id:'cream-17',name:'Sunblock SPF 80',cat:'Creams',price:1100,desc:'Maximum protection sunblock SPF 80 for outdoor use',img:'images/cream-spf80.png'},
  {id:'cream-18',name:'Extreme Day Skin Lotion',cat:'Creams',price:800,desc:'Daytime protection lotion for hydrated & shielded skin',img:'images/cream-day-lotion.png'},
  {id:'cream-19',name:'Soothing Lotion',cat:'Creams',price:750,desc:'Calming lotion for sensitive & irritated skin relief',img:'images/cream-soothing.png'},
  {id:'cream-20',name:'Prickly Heat Lotion',cat:'Creams',price:700,desc:'Cooling formula for instant prickly heat relief',img:'images/cream-prickly-heat.png'},

  {id:'serum-1',name:'Hyaluronic Acid Serum',cat:'Serums',price:1800,desc:'Deep hydration & plumping effect',img:'images/serum-hyaluronic.png'},
  {id:'serum-2',name:'Salicylic Acid Serum',cat:'Serums',price:1500,desc:'Unclogs pores & clears breakouts',img:'images/serum-salicylic.png'},
  {id:'serum-3',name:'Zinc PCA Serum',cat:'Serums',price:1400,desc:'Controls oil & reduces blemishes',img:'images/serum-zinc-pca.png'},
  {id:'serum-4',name:'Alpha Arbutin Serum',cat:'Serums',price:1600,desc:'Fades dark spots & evens skin tone',img:'images/serum-alpha-arbutin.png'},
  {id:'serum-5',name:'Vitamin C Serum',cat:'Serums',price:1500,desc:'Brightens skin & boosts radiance',img:'images/serum-vitamin-c.png'},
  {id:'serum-6',name:'Vitamin B-5 Serum',cat:'Serums',price:1450,desc:'Deep moisture & skin barrier repair',img:'images/serum-vitamin-b5.png'},
  {id:'serum-7',name:'Glutathione Serum',cat:'Serums',price:1900,desc:'Whitening & antioxidant protection',img:'images/serum-glutathione.png'},
  {id:'serum-8',name:'Niacinamide Serum',cat:'Serums',price:1400,desc:'Minimizes pores & controls oil',img:'images/serum-niacinamide.png'},
  {id:'serum-9',name:'All-in-One Serum',cat:'Serums',price:1700,desc:'Multi-action formula for hydration, brightening & repair',img:'images/serum-all-in-one.png'},
  {id:'serum-10',name:'Glycolic Acid Serum',cat:'Serums',price:1600,desc:'AHA exfoliant for smoother, radiant & even skin tone',img:'images/serum-glycolic.png'},
  {id:'serum-11',name:'Multipurpose Serum',cat:'Serums',price:1550,desc:'Versatile serum for daily skin care & treatment',img:'images/serum-multipurpose.png'},

  {id:'fw-1',name:'Foaming Face Wash',cat:'Face Wash',price:550,desc:'Deep cleansing & refreshing foam',img:'images/fw-foaming.png'},
  {id:'fw-2',name:'Creamy Face Wash',cat:'Face Wash',price:600,desc:'Gentle nourishing cream cleanse',img:'images/fw-creamy.png'},
  {id:'fw-3',name:'Gel Face Wash (Transparent)',cat:'Face Wash',price:500,desc:'Purifying transparent gel formula',img:'images/fw-gel.png'},
  {id:'fw-4',name:'Pearly Shine Face Wash',cat:'Face Wash',price:650,desc:'Pearl extracts for radiant glow',img:'images/fw-pearly-shine.png'},
  {id:'fw-5',name:'Vitamin C Face Wash',cat:'Face Wash',price:650,desc:'Brightens & evens skin tone daily',img:'images/fw-vitaminc.png'},
  {id:'fw-6',name:'Vitamin B-3 Face Wash',cat:'Face Wash',price:620,desc:'Niacinamide for smooth clear skin',img:'images/fw-vitaminb3.png'},
  {id:'fw-7',name:'Charcoal Face Wash',cat:'Face Wash',price:600,desc:'Deep pore cleansing with activated charcoal',img:'images/fw-charcoal.png'},
  {id:'fw-8',name:'Brightening Face Wash',cat:'Face Wash',price:580,desc:'Glowing & luminous skin formula',img:'images/fw-brightening.png'},
  {id:'fw-9',name:'Men\'s Face Wash',cat:'Face Wash',price:600,desc:'Powerful deep cleanse for men\'s skin',img:'images/fw-mens.png'},
  {id:'fw-10',name:'Rice Face Wash',cat:'Face Wash',price:580,desc:'Rice extract for soft & bright skin',img:'images/fw-rice.png'},
  {id:'fw-11',name:'Turmeric Face Wash',cat:'Face Wash',price:570,desc:'Natural turmeric for clear glowing skin',img:'images/fw-turmeric.png'},
  {id:'fw-12',name:'Herbal Face Wash',cat:'Face Wash',price:560,desc:'Natural herbs for gentle daily cleanse',img:'images/fw-herbal.png'},
  {id:'fw-13',name:'Anti Acne Face Wash',cat:'Face Wash',price:620,desc:'Fights acne & prevents future breakouts',img:'images/fw-anti-acne.png'},
  {id:'fw-14',name:'Gold Face Wash',cat:'Face Wash',price:750,desc:'24K gold for luxury skin brightening',img:'images/fw-gold.png'},

  {id:'pj-1',name:'Colored Petroleum Jelly',cat:'Petroleum Jelly',price:380,desc:'Tinted lip & skin care',img:'images/pj-colored.png'},
  {id:'pj-2',name:'Original Petroleum Jelly',cat:'Petroleum Jelly',price:350,desc:'Classic skin protection',img:'images/pj-original.png'},
  {id:'pj-3',name:'Scented Petroleum Jelly',cat:'Petroleum Jelly',price:400,desc:'Fragrant moisturizing jelly',img:'images/pj-scented.png'},

  {id:'lot-1',name:'Brightening Lotion',cat:'Lotions',price:850,desc:'Evens tone & boosts skin radiance',img:'images/lot-brightening.png'},
  {id:'lot-2',name:'Niacinamide Lotion',cat:'Lotions',price:800,desc:'Minimizes pores & controls oil',img:'images/lot-niacinamide.png'},
  {id:'lot-3',name:'Vitamin C Lotion',cat:'Lotions',price:850,desc:'Brightens & protects with Vitamin C',img:'images/lot-vitamin-c.png'},
  {id:'lot-4',name:'Vitamin E Lotion',cat:'Lotions',price:750,desc:'Antioxidant-rich deep moisturizer',img:'images/lot-vitamin-e.png'},
  {id:'lot-5',name:'Cleansing Lotion',cat:'Lotions',price:700,desc:'Gentle cleanse & soft skin daily',img:'images/lot-cleansing.png'},
  {id:'lot-6',name:'Honey Lotion',cat:'Lotions',price:780,desc:'Honey extracts for nourished skin',img:'images/lot-honey.png'},
  {id:'lot-7',name:'Cocoa Butter Lotion',cat:'Lotions',price:800,desc:'Rich cocoa for smooth & supple skin',img:'images/lot-cocoa-butter.png'},
  {id:'lot-8',name:'Lavender Lotion',cat:'Lotions',price:750,desc:'Calming lavender for relaxed skin',img:'images/lot-lavender.png'},
  {id:'lot-9',name:'Aloe Vera Lotion',cat:'Lotions',price:700,desc:'Soothing & cooling aloe formula',img:'images/lot-aloe-vera.png'},
  {id:'lot-10',name:'Multi-Purpose Lotion',cat:'Lotions',price:720,desc:'All-in-one formula for face & body',img:'images/lot-multi-purpose.png'},

  {id:'sh-1',name:'Keratin Shampoo',cat:'Shampoo & Conditioner',price:900,desc:'Smoothens, repairs & strengthens hair',img:'images/sh-keratin.png'},
  {id:'sh-2',name:'Anti-Dandruff Shampoo',cat:'Shampoo & Conditioner',price:650,desc:'Eliminates dandruff & flakes effectively',img:'images/sh-anti-dandruff.png'},
  {id:'sh-3',name:'Sulfate-Free Shampoo',cat:'Shampoo & Conditioner',price:800,desc:'Gentle cleanse without harsh sulfates',img:'images/sh-sulfate-free.png'},
  {id:'sh-4',name:'Herbal Shampoo',cat:'Shampoo & Conditioner',price:700,desc:'Natural herbs for healthy hair growth',img:'images/sh-herbal.png'},
  {id:'sh-5',name:'Onion Shampoo',cat:'Shampoo & Conditioner',price:750,desc:'Onion extract to reduce hair fall',img:'images/sh-onion.png'},
  {id:'sh-6',name:'Egg Shampoo',cat:'Shampoo & Conditioner',price:720,desc:'Protein-rich formula for strong hair',img:'images/sh-egg.png'},
  {id:'sh-7',name:'Rice Shampoo',cat:'Shampoo & Conditioner',price:680,desc:'Rice water for smooth & shiny hair',img:'images/sh-rice.png'},
  {id:'sh-8',name:'Coconut Shampoo',cat:'Shampoo & Conditioner',price:700,desc:'Deep nourishment with coconut extracts',img:'images/sh-coconut.png'},
  {id:'sh-9',name:'Almond Shampoo',cat:'Shampoo & Conditioner',price:750,desc:'Almond oil for soft & silky hair',img:'images/sh-almond.png'},
  {id:'sh-10',name:'Strengthening Shampoo',cat:'Shampoo & Conditioner',price:780,desc:'Fortifies & prevents hair breakage',img:'images/sh-strengthening.png'},
  {id:'sh-11',name:'Men\'s Shampoo',cat:'Shampoo & Conditioner',price:700,desc:'Powerful scalp care for men\'s hair',img:'images/sh-mens.png'},
  {id:'sh-12',name:'Conditioner',cat:'Shampoo & Conditioner',price:750,desc:'Deep conditioning for soft, smooth & manageable hair',img:'images/sh-conditioner.png'},
  {id:'sh-13',name:'Anti-Lice Shampoo',cat:'Shampoo & Conditioner',price:800,desc:'Effective anti-lice formula safe for regular use',img:'images/sh-anti-lice.png'},
  {id:'sh-14',name:'Amla Shampoo',cat:'Shampoo & Conditioner',price:720,desc:'Amla extract for stronger, thicker hair growth',img:'images/sh-amla.png'},
  {id:'sh-15',name:'Amla Conditioner',cat:'Shampoo & Conditioner',price:750,desc:'Amla-infused conditioning for nourished hair',img:'images/sh-amla-conditioner.png'},
  {id:'sh-16',name:'Deep Conditioner',cat:'Shampoo & Conditioner',price:850,desc:'Intensive deep conditioning treatment for dry & damaged hair',img:'images/sh-deep-conditioner.png'},
  {id:'sh-17',name:'Leave-in Conditioner',cat:'Shampoo & Conditioner',price:900,desc:'No-rinse leave-in formula for all-day moisture & softness',img:'images/sh-leave-in.png'},
  {id:'sh-18',name:'Color Protect Conditioner',cat:'Shampoo & Conditioner',price:950,desc:'Guards color-treated hair from fading & damage',img:'images/sh-color-protect.png'},
  {id:'sh-19',name:'Keratin Conditioner',cat:'Shampoo & Conditioner',price:1000,desc:'Keratin-infused conditioner for smooth, frizz-free hair',img:'images/sh-keratin-conditioner.png'},
  {id:'sh-20',name:'Onion Conditioner',cat:'Shampoo & Conditioner',price:800,desc:'Onion extract conditioner to strengthen & reduce hair fall',img:'images/sh-onion-conditioner.png'},
  {id:'sh-21',name:'Argan Conditioner',cat:'Shampoo & Conditioner',price:1050,desc:'Argan oil conditioning for silky, glossy & nourished hair',img:'images/sh-argan-conditioner.png'},
  {id:'sh-22',name:'Herbal Conditioner',cat:'Shampoo & Conditioner',price:780,desc:'Natural herbal blend for gentle conditioning & scalp health',img:'images/sh-herbal-conditioner.png'},
  {id:'sh-23',name:'Coconut Conditioner',cat:'Shampoo & Conditioner',price:820,desc:'Coconut milk conditioning for deep moisture & shine',img:'images/sh-coconut-conditioner.png'},

  {id:'hc-1',name:'Hair Tonic',cat:'Hair Care',price:850,desc:'Stimulates scalp & promotes healthy hair growth',img:'images/hc-tonic.png'},
  {id:'hc-2',name:'Hair Serum',cat:'Hair Care',price:1100,desc:'Lightweight serum for frizz control & shine',img:'images/hc-serum.png'},
  {id:'hc-3',name:'Hair Oil',cat:'Hair Care',price:900,desc:'Nourishing blend for deep hair & scalp conditioning',img:'images/hc-oil.png'},
  {id:'hc-4',name:'Hair Gel',cat:'Hair Care',price:650,desc:'Strong hold gel for styling & long-lasting control',img:'images/hc-gel.png'},
  {id:'hc-5',name:'Hair Cream',cat:'Hair Care',price:780,desc:'Moisturising cream for smooth, defined & healthy hair',img:'images/hc-cream.png'},

  {id:'eo-1',name:'Coconut Oil',cat:'Essential Oils',price:650,desc:'Pure cold-pressed coconut oil for skin & hair',img:'images/eo-coconut.png'},
  {id:'eo-2',name:'Sunflower Oil',cat:'Essential Oils',price:600,desc:'Light moisturising oil rich in Vitamin E',img:'images/eo-sunflower.png'},
  {id:'eo-3',name:'Jojoba Oil',cat:'Essential Oils',price:900,desc:'Skin-balancing jojoba for face, hair & body',img:'images/eo-jojoba.png'},
  {id:'eo-4',name:'Argan Oil',cat:'Essential Oils',price:1200,desc:'Liquid gold from Morocco for hair & skin repair',img:'images/eo-argan.png'},
  {id:'eo-5',name:'Neem Oil',cat:'Essential Oils',price:700,desc:'Potent neem oil for acne, scalp & skin health',img:'images/eo-neem.png'},
  {id:'eo-6',name:'Amla Oil',cat:'Essential Oils',price:650,desc:'Traditional amla oil for hair strength & growth',img:'images/eo-amla.png'},
  {id:'eo-7',name:'Canola Oil',cat:'Essential Oils',price:550,desc:'Light multi-purpose oil for skin moisturising',img:'images/eo-canola.png'},
  {id:'eo-8',name:'Moringa Oil',cat:'Essential Oils',price:950,desc:'Nutrient-rich moringa for skin & hair nourishment',img:'images/eo-moringa.png'},
  {id:'eo-9',name:'Onion Oil',cat:'Essential Oils',price:700,desc:'Onion extract oil to reduce hair fall & boost growth',img:'images/eo-onion.png'},
  {id:'eo-10',name:'Almond Oil',cat:'Essential Oils',price:800,desc:'Sweet almond oil for deep skin & hair moisture',img:'images/eo-almond.png'},
  {id:'eo-11',name:'Kalonji Oil',cat:'Essential Oils',price:750,desc:'Black seed oil for immunity, skin & hair wellness',img:'images/eo-kalonji.png'},
  {id:'eo-12',name:'Sesame Seed Oil',cat:'Essential Oils',price:650,desc:'Traditional sesame oil for deep nourishment',img:'images/eo-sesame.png'},
  {id:'eo-13',name:'Lavender Oil',cat:'Essential Oils',price:850,desc:'Calming lavender oil for relaxation & skin care',img:'images/eo-lavender.png'},

  {id:'facial-1',name:'Face Mask',cat:'Facial',price:650,desc:'Deep cleansing mask for purified & refreshed skin',img:'images/facial-mask.png'},
  {id:'facial-2',name:'Massage Cream',cat:'Facial',price:700,desc:'Smooth massage cream for relaxed & nourished skin',img:'images/facial-massage-cream.png'},
  {id:'facial-3',name:'Face Scrub',cat:'Facial',price:620,desc:'Exfoliating scrub for bright & smooth skin texture',img:'images/facial-scrub.png'},
  {id:'facial-4',name:'Skin Polish',cat:'Facial',price:680,desc:'Microbead polish for refined & luminous skin',img:'images/facial-skin-polish.png'},
  {id:'facial-5',name:'Double Action Cleanser',cat:'Facial',price:750,desc:'Dual-phase cleanser removes makeup & deep cleanses',img:'images/facial-double-cleanser.png'},
  {id:'facial-6',name:'Face Cleanser',cat:'Facial',price:600,desc:'Gentle daily cleanser for fresh & clear skin',img:'images/facial-cleanser.png'},
  {id:'facial-7',name:'Peel-Off Mask',cat:'Facial',price:680,desc:'Peeling mask to remove blackheads & impurities',img:'images/facial-peel-off.png'},
  {id:'facial-8',name:'Milk Toner',cat:'Facial',price:580,desc:'Milky toner for soft, hydrated & balanced skin',img:'images/facial-milk-toner.png'},
  {id:'facial-9',name:'Skin Toner',cat:'Facial',price:600,desc:'Refreshing toner to restore pH & minimize pores',img:'images/facial-toner.png'},
  {id:'facial-10',name:'All-in-One Facial Cream',cat:'Facial',price:900,desc:'Complete care cream for cleanse, tone & moisturise',img:'images/facial-all-in-one.png'},
  {id:'facial-11',name:'Blackhead Mask',cat:'Facial',price:650,desc:'Targeted mask to extract & prevent blackheads',img:'images/facial-blackhead-mask.png'},
  {id:'facial-12',name:'Charcoal Mask',cat:'Facial',price:700,desc:'Activated charcoal for deep pore detox & cleanse',img:'images/facial-charcoal-mask.png'},
  {id:'facial-13',name:'Bleach Powder',cat:'Facial',price:450,desc:'Skin bleaching powder for even & lighter complexion',img:'images/facial-bleach-powder.png'},
  {id:'facial-14',name:'Bleach Cream',cat:'Facial',price:500,desc:'Smooth bleach cream for gentle skin lightening',img:'images/facial-bleach-cream.png'},
  {id:'facial-15',name:'Bleach Hair Powder',cat:'Facial',price:480,desc:'Hair bleaching powder for face & body hair removal',img:'images/facial-bleach-hair.png'},
  {id:'facial-16',name:'Cream Developer 10 Volume',cat:'Facial',price:400,desc:'10 Vol developer for gentle colour & bleach mixing',img:'images/facial-dev-10.png'},
  {id:'facial-17',name:'Cream Developer 20 Volume',cat:'Facial',price:400,desc:'20 Vol developer for standard colour processing',img:'images/facial-dev-20.png'},
  {id:'facial-18',name:'Cream Developer 30 Volume',cat:'Facial',price:420,desc:'30 Vol developer for lifting & stronger colour',img:'images/facial-dev-30.png'},
  {id:'facial-19',name:'Cream Developer 40 Volume',cat:'Facial',price:450,desc:'40 Vol developer for maximum lift & bleaching',img:'images/facial-dev-40.png'},

  {id:'bk-1',name:'Baby Lotion',cat:'Baby & Kids',price:650,desc:'Gentle moisturizing lotion for soft baby skin',img:'images/bk-lotion.png'},
  {id:'bk-2',name:'Baby Cream',cat:'Baby & Kids',price:600,desc:'Nourishing cream for delicate baby skin',img:'images/bk-cream.png'},
  {id:'bk-3',name:'Baby Shampoo',cat:'Baby & Kids',price:550,desc:'Tear-free gentle formula for baby hair',img:'images/bk-shampoo.png'},
  {id:'bk-4',name:'Baby Face Wash',cat:'Baby & Kids',price:520,desc:'Mild cleansing for baby\'s sensitive face',img:'images/bk-facewash.png'},
  {id:'bk-5',name:'Baby Body Wash',cat:'Baby & Kids',price:580,desc:'Soft & gentle full-body baby wash',img:'images/bk-body-wash.png'},
  {id:'bk-6',name:'Baby Oil',cat:'Baby & Kids',price:500,desc:'Pure moisturizing oil for baby massage',img:'images/bk-oil.png'},
  {id:'bk-7',name:'Baby Petroleum Jelly',cat:'Baby & Kids',price:400,desc:'Safe & gentle skin protection for babies',img:'images/bk-pjelly.png'},
  {id:'bk-8',name:'Kids Shampoo',cat:'Baby & Kids',price:580,desc:'Fun & gentle shampoo for kids\' hair',img:'images/bk-kids-shampoo.png'},
];

function orderNow(name) {
  const msg = `Hello ACM Asia Cosmetics! 👋\n\nI would like to place an order for:\n📦 *${name}*\n📦 Quantity: 100+ pcs\n\nPlease share pricing and delivery details. Thank you!`;
  window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`, '_blank');
}
